title: 学习笔记
description: 个人学习记录与分享
baseurl: ""
url: "https://Larry-lyx.github.io"
author: Larry-lyx

# 主题设置
theme: minima  # 可以更换为其他支持的主题

# 插件配置
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-katex  # 用于渲染数学公式
  - jekyll-highlight  # 用于代码高亮

# 数学公式配置
katex:
  rendering: mathml  # 或 svg

# 分页配置
paginate: 10
paginate_path: "/page:num/"